Implement WeatherForecast telemetry
lsst-ts/ts_weatherforecast pull request #2
Opened 2022-11-03 22:37 UTC by couger01

* Add eups and pyproject.toml support
* Add pre-commit support
* Add doc template
* Add Jenkinsfile
* Add scons boilerplate
* Move plantuml files to doc folder
* Remove development python files
* Add CSC unit test
* Add LICENSE

2022-11-04 13:27 UTC, wvreeven requested changes
This is an improvement over the previous code base, but it can be improved much more. I will probably have more comments once you have processed the current ones.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +import os
Please sort the imports with isort.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +LATITUDE = -30.24
Please move this and the next 5 lines to the CSC configuration.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +__all__ = ["WeatherForecastCSC"]
Please add a license header and do that in all other Python files as well.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +class WeatherForecastCSC(salobj.BaseCsc):
Please add a class doc string.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +    async def telemetry(self):
Please add a doc string describing what this function does.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +            with open("forecast-test.json") as f:
I am surprised this works. Please add a proper Path relative to the current file. And take into account that you need to move this file as explained in my comment for the file.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +                "http://my.meteoblue.com", raise_for_status=True
Why add a SITE_URL constant and not use it? Please extract this and all other URL strings to config parameters.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +                    with open("forecast.json", "wb") as fd:
Please rewrite this and the next few lines to store the contents of the file in memory instead of relying on writing to disk.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +        await asyncio.sleep(12 * 3600)
Please extract to a config option, or at least a constant, and use that here.

2022-11-04 13:27 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +        modelrun_utc = datetime.datetime.strptime(
I think you can simply use the datetime.datetime.timestamp() function instead and ditch the calendar import. You appear to do this conversion several times below so extract to a function and call that here and everywhere else.

2022-11-04 13:27 UTC, wvreeven commented on tests/test_csc.py
> +            assert -3 == metadata.timeOffset
Please add functions that test the other telemetry as well.

2022-11-04 13:27 UTC, wvreeven commented on ups/ts_weatherforecast.table
> +envPrepend(PYTHONPATH, ${PRODUCT_DIR}/python)
Please add dependencies for salobj and utils, otherwise EUPS cannot work properly.

2022-11-07 12:01 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +class WeatherForecastCSC(salobj.BaseCsc):
Dude, adding a doc string means adding a complete doc string. You didn't describe the parameters, nor the attributes. Also please add a short description of what the CSC is supposed to do and expand CSC to `Commandable SAL Component`.

2022-11-07 12:01 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +        """Convert datetime string to unix timestamp
Please end the sentence in a `.`.

2022-11-07 12:02 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +    async def telemetry(self):
Again, please add a short description of what the telemetry loop is supposed to do.

2022-11-07 12:03 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +        modelrun_utc = datetime.datetime.strptime(
Can you please explain why you didn't decide to do this in a comment to this conversation?

2022-11-07 12:31 UTC, couger01 commented on python/lsst/ts/weatherforecast/csc.py
> +LATITUDE = -30.24
I don't believe that this is necessary to be configurable because I see the the information as being pretty static but if you believe it should be. I will do it.

2022-11-07 12:34 UTC, couger01 commented on python/lsst/ts/weatherforecast/csc.py
> +        modelrun_utc = datetime.datetime.strptime(
I missed it.

2022-11-07 12:38 UTC, couger01 commented on python/lsst/ts/weatherforecast/__init__.py
> +# Developed for the LSST Telescope and Site Systems.
Grabbed an old header by accident.

2022-11-07 14:55 UTC, wvreeven approved these changes
Looks good to me. Thanks for all the changes. I left a few more comments for you too.

2022-11-07 14:55 UTC, wvreeven commented on conda/meta.yaml
> +        - py.test
Oops I missed this one. Please change to `pytest`.

2022-11-07 14:55 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +LATITUDE = -30.24
It turns out that the CSC is set to be non-configurable so let's leave it as is.

2022-11-07 14:55 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +        The interval at which the telemetry loop is run.
Please add the unit here too.

2022-11-07 14:55 UTC, wvreeven commented on python/lsst/ts/weatherforecast/csc.py
> +        The last time that the forecast was updated.
Please indicate that the time is in UTC.

2022-11-07 15:52 UTC, merged