tickets/DM 37367
lsst-ts/ts_weatherforecast pull request #7
Opened 2022-12-16 18:11 UTC by couger01

- Add MockServer and fix reading data from server
- Make enable_cmdline_state true
- Make SITE_URL global in simulation mode
- Make get URL correct
- Clean extraTerrestrialRadiationBackwards values

2022-12-16 22:00 UTC, r-owen requested changes
A very welcome addition. I do have a few requests, the most important of which are probably:
* Raise an error if METEOBLUE_API_KEY is not defined (e.g. in the CSC constructor)
* Move the mock server code to its own module
* Allow port=0 for the mock server.

2022-12-16 22:05 UTC, r-owen commented on pyproject.toml
> +requires = ["setuptools>=45", "setuptools-scm[toml]>=6.2"]
Also I gently suggest at line 38 and 39 to eliminate the double quotes around line length in:
```
flake8-max-line-length = "110"		flake8-max-line-length = "110"
flake8-max-doc-length = "79"		flake8-max-doc-length = "79"
```

VSCode does not seem to see flake8-max-line-length=110 when I view this project. I don't see that with other packages. Is there a problem with the configuration? User error?

2022-12-16 22:52 UTC, couger01 commented on pyproject.toml
> +requires = ["setuptools>=45", "setuptools-scm[toml]>=6.2"]
Both work.

2022-12-16 23:01 UTC, couger01 commented on python/lsst/ts/weatherforecast/csc.py
> +async def make_app():
I did try to make a class, but I was unable to figure the magic incantation to make all the pieces work correctly. However I will move all of the functions related to the mock server to its own module in order to reduce confusion.

2022-12-16 23:03 UTC, couger01 commented on python/lsst/ts/weatherforecast/csc.py
> +    enable_cmdline_state = True
In my case, Michael told me to consider the idea since this CSC contains no commands and simply transmits forecast data. I guess that's permission by implication.

2022-12-16 23:21 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +async def make_app():
Please try again. Look at the example. I can help if wanted

2022-12-16 23:22 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +    enable_cmdline_state = True
Perfect

2022-12-19 22:23 UTC, r-owen requested changes
Nice improvements.

My main concern at this point is that the telemetry loop is not actually a loop. Also the way you extract data from the response seems overly complicated and I think you are ignoring bad response status codes.

2022-12-19 22:23 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +                        fd.write(decoded_chunk)
Is this loop and the use of StringIO actually needed? I have never had to do that before. What happens if you just use use the naive thing of grabbing all the data at once:
```
async with session.get(
    "/packages/trendpro-1h_trendpro-day",
    params=params,
) as resp:
    if response.status != http.SUCCESS:
         # do something sensible on error, such as log and error and give up for this iteration
    response_data = resp.json()  # you call this df; I hope you can use a clearer name
```

2022-12-19 22:23 UTC, r-owen commented on python/lsst/ts/weatherforecast/mock_server.py
> +            raise RuntimeError("Application not running; Call start.")
I strongly suggest coding this so you can call it even if already cleaned up. That makes the API easier to use. (Also, the suggestion to "call start" in this method seems rather surprising). Consider something like this:
```
if self.runner is not None:
    runner = self.runner
    self.runner = None
    await self.runner.cleanup()
```

2022-12-19 22:23 UTC, r-owen commented on python/lsst/ts/weatherforecast/mock_server.py
> +        """Return the canned json response.
Please document the parameter. Is it useful for anything?

2022-12-19 22:23 UTC, r-owen commented on python/lsst/ts/weatherforecast/mock_server.py
> +            df = json.load(f)
I gently suggest reading this once, when the object is constructed, instead of re-reading the file each time you request a forecast.

2022-12-19 22:23 UTC, r-owen commented on python/lsst/ts/weatherforecast/mock_server.py
> +        server = self.site._server
You only use this variable if self.port == 0, so please move this into the `if self.port == 0` block that starts on the next line.

2022-12-19 22:23 UTC, r-owen commented on python/lsst/ts/weatherforecast/mock_server.py
> +            [web.get("/packages/trendpro-1h_trendpro-day", self.get_forecast)]
I suggest that this endpoint be a constant that both this code and the CSC can access (e.g. from a new module that has a few useful constants in it).

That way if the MeteoBlue endpoint changes. you only have to change this string in one place. Also the value is both long and non-obvious, so a named constant may make the code easier to understand.

2022-12-19 23:15 UTC, couger01 commented on pyproject.toml
> +requires = ["setuptools>=45", "setuptools-scm[toml]>=6.2"]
I'm not sure, I don't see any issue with my VSCode but it could be my setup is different from yours.

2022-12-19 23:59 UTC, r-owen approved these changes
Looks good. A few minor suggestions to consider before merging.

2022-12-19 23:59 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +                        self.log.info("Session gotten.")
I gently suggest deleting this line. The log.debug is more informative and gives useful info if wanted, without cluttering the log most of the time.

2022-12-19 23:59 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +                modelrun_utc = modelrun_utc.timestamp()
Please don't use the same variable for two different types. If you don't need the intermediate value at all you can just call timestamp one line above. Or you can call the intermediate value modelrun_utc_datetime?

Similarly for the next timestamp. In fact it might be worth writing tiny function that converts a time field to the format you want.

2022-12-19 23:59 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +                    converted_timestamp.append(timestamp)
I think these 4 lines would make a nice list comprehension. Also, please consider plural names for lists of values:
```
timestamps = trend_hour_fld["time"]
converted_timestamps = [self.convert_time(timestamp) for timestamp in timestamps]
```

2022-12-19 23:59 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +                    converted_timestamp.append(timestamp)
Another candidate for a list comprehension (identical to the one above, just a different field name).

2022-12-19 23:59 UTC, r-owen commented on python/lsst/ts/weatherforecast/csc.py
> +                await server.stop()
I strongly suggest canceling telemetry_task *before* closing the mock server. That way you don't have to worry about the telemetry loop unexpectedly reading from a closed server.

2022-12-20 03:21 UTC, merged